In [2]:
import torch
torch.__version__

'2.6.0+cpu'

In [3]:
##creating Tensors
#Scaler
#vector
#matrix
#tensor
#Tensor is a multidimensional matrix containing a single data type
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
#scaler to normal integer
scaler.item()

7

In [5]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
 #MATRIX
MATRIX = torch.tensor([[7,9],
                      [9,10]])
MATRIX

tensor([[ 7,  9],
        [ 9, 10]])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
##Random Tensors
#create a random tensor of sixe (3,4)
torch.manual_seed(42)
random_number = torch.rand(3,4)
random_number

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [21]:
## Zeros & Ones
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(size=(4,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

----

In [33]:
### Creating a range of tensors with torch.arange
a = torch.arange(0,10,2)
a

tensor([0, 2, 4, 6, 8])

In [48]:
## Tensor Datatypes
#Float32 tensor
x = torch.tensor([3.0,6.0,7.2],
                              dtype=torch.float32,
                              device=None,
                              requires_grad=False)
x

tensor([3.0000, 6.0000, 7.2000])

In [49]:
float_16_tensor = x.type(torch.float16)
float_16_tensor

tensor([3.0000, 6.0000, 7.1992], dtype=torch.float16)

In [50]:
##Manipulating Tensors
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [52]:
tensor * 10

tensor([10, 20, 30])

In [53]:
##Pytorch inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [58]:
## MAtrix Multiplication
## Two ways in performing matrix multiplication

#Element Wise Multiplication
print(tensor,"*",tensor)
print(tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
tensor([1, 4, 9])


In [59]:
#Matrix Multiplication (Dot Product)
torch.matmul(tensor,tensor)

tensor(14)

In [63]:
#Transpose Matrix
tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensorB = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [65]:
new_tensor = torch.matmul(tensorA, tensorB.T)
new_tensor

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [67]:
## Finding min, max, sum, etc
min = torch.min(new_tensor)
min

tensor(23)

In [69]:
#Torch.mean doesnt work on int64 or Long datatype, thats why
#converting the datatype to float32
torch.mean(new_tensor.type(torch.float32))

tensor(67.)

In [70]:
array_tensor = torch.arange(1,100,10)
array_tensor

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [71]:
#Fin minimum element index
min = torch.argmin(array_tensor)
min

tensor(0)

In [72]:
#Find max
max = torch.argmax(array_tensor)
max

tensor(9)

## Reshape of Tensor

In [74]:
arr = torch.arange(1.,13.)
arr, arr.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [75]:
arr.reshape(4,3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [88]:
## Numpy MAp Function
import numpy as np
numpy_arr = np.arange(1,10,2)
print(f"Original Array : {numpy_arr}")

val_arr = list(map(lambda x:x**2, numpy_arr))
print(f"Modified array : {val_arr}")

Original Array : [1 3 5 7 9]
Modified array : [1, 9, 25, 49, 81]


In [92]:
#torch.squeeze -> Removes the single dimension
#torch.unsqueeze -> Adds a single dimension to the target tensor
arr = arr.reshape(1,12)
print(f"Originial array :{arr}")
print(f"Originial shpae :{arr.shape}")

print(f"\nSqueezed arr : {arr.squeeze()}")
print(f"\nSqueezed arr shape : {arr.squeeze().shape}")

Originial array :tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
Originial shpae :torch.Size([1, 12])

Squeezed arr : tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

Squeezed arr shape : torch.Size([12])


In [94]:
arr.unsqueeze(dim=0).shape

torch.Size([1, 1, 12])

In [95]:
arr

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [96]:
##Numpy array to Tensor
import torch
import numpy as np

numpy_arr = np.arange(1.0,8.0)
numpy_arr

array([1., 2., 3., 4., 5., 6., 7.])

In [97]:
arr_tensor = torch.from_numpy(numpy_arr)
arr_tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [98]:
arr_tensor.dtype

torch.float64

## Running tensors and PyTorch object in GPUs

In [99]:
### 1. Getting a GPU
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [100]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'